import BlackSwatch from '../../assets2/swatches/BLACK-SWATCH.png';
import CherryRedSwatch from '../../assets2/swatches/CHERRY RED -SWATCH.png';
import ChocolateSwatch from '../../assets2/swatches/CHOCOLATE -SWATCH.png';
import CoffeeSwatch from '../../assets2/swatches/COFFEE -SWATCH.png';
import DarkPurpleSwatch from '../../assets2/swatches/DARK PURPLE -SWATCH.png';
import ForrestGreenSwatch from '../../assets2/swatches/FORREST GREEN-SWATCH.png';
import GraySwatch from '../../assets2/swatches/GRAY -SWATCH.png';
import HotPinkSwatch from '../../assets2/swatches/HOT PINK -SWATCH.png';
import JetBlueSwatch from '../../assets2/swatches/JET BLUE -SWATCH.png';
import LavenderSwatch from '../../assets2/swatches/LAVENDER -SWATCH.png';
import LeafGreenSwatch from '../../assets2/swatches/LEAF GREEN -SWATCH.png';
import PicachoBlueSwatch from '../../assets2/swatches/PICACHO BLUE - SWATCH.png';
import PicachoYellowSwatch from '../../assets2/swatches/PICACHO YELLOW-SWATCH.png';
import SacramentoGreenSwatch from '../../assets2/swatches/SACRAMENTO GREEN -SWATCH.png';
import SalmonSwatch from '../../assets2/swatches/SALMON -SWATCH.png';
import SkyBlueSwatch from '../../assets2/swatches/SKY BLUE -SWATCH.png';
import TangerineSwatch from '../../assets2/swatches/TANGERINE -SWATCH.png';
import TurquoiseSwatch from '../../assets2/swatches/TURQUOISE -SWATCH.png';
import WhiteSwatch from '../../assets2/swatches/WHITE-SWATCH.png';
import ArmySwatch from '../../assets2/swatches/ARMY-SWATCH.png';
import PlumSwatch from '../../assets2/swatches/PLUM-SWATCH.png';
import PaleYellowSwatch from '../../assets2/swatches/PALE YELLOW-SWATCH.png';
